### PR TITLE
feat/slicing new design read insightful section at article page

### PR DESCRIPTION
**Pull request by dzarurizkyy**
Completed slicing new design read insightful section on article page.

### CODE REVIEW

**Review by nugrahaAdhitama — CHANGES_REQUESTED** [review]
### `src/app/articles/page.tsx` - Swiper Configuration
## Orignial Code:
```
<Swiper
  slidesPerView={1}
  spaceBetween={20}
  navigation={true}
  breakpoints={{
    640: {
      slidesPerView: 2,
    },
    1024: {
      slidesPerView: 1, // Potential mistake here
    },
  }}
  modules={[Navigation]}
>
```

## Recommended Change:
To utilize screen space more efficiently on larger devices, consider increasing the number of slides per view at the 1024px breakpoint.
```
<Swiper
  slidesPerView={1}
  spaceBetween={20}
  navigation={true}
  breakpoints={{
    640: {
      slidesPerView: 2,
    },
    1024: {
      slidesPerView: 3, // Adjusted for better space utilization
    },
  }}
  modules={[Navigation]}
>
```
The adjustment ensures that the available screen space on larger devices is used more effectively, providing a better user experience.

### `src/components/icons/TimeIcon.tsx` - Component Props Typing
## Original Code
```
const TimeIcon = (props: any) => {
  const {width, height, stroke} = props
  ...
}
```
## Recommended Code
Define a TypeScript interface for the component props to improve type safety and documentation.
```
interface TimeIconProps {
  width: string;
  height: string;
  stroke: string;
}

const TimeIcon = ({ width, height, stroke }: TimeIconProps) => {
  ...
}
```
By specifying types for the component's props, we enhance the code's readability and prevent potential type-related bugs. This practice also serves as self-documentation for the component's API.

### `src/utils/formatArticleTitle.ts` - Improve Type Safety
## Original Code
```
export const formatArticleTitle = (data: any, split: number) => {
  ...
};
```
## Recommended Code
Specify the type of data as string to improve type safety.
```
export const formatArticleTitle = (data: string, split: number): string => {
  ...
};
```
Specifying `data` as a `string` type instead of `any` ensures that the function can only be called with the appropriate type of argument, reducing the likelihood of runtime errors.

**Review by dzarurizkyy — COMMENTED** [review]
Completed implement Typescript interfaces to improve code readability and prevent potential type-related bugs.

**Review by nugrahaAdhitama — CHANGES_REQUESTED** [review]
Please resolve the conflict first

**Comment by dzarurizkyy** [comment]
Completed fix merge conflict

**Pull request merged**
