### PR TITLE
feat/redesign hero section on articles page

### PR DESCRIPTION
**Pull request by dzarurizkyy**
Slicing latest hero section design is complete, it is also already responsive on various devices, and animations are running smoothly.

### CODE REVIEW

**Review by candidatecollege — CHANGES_REQUESTED** [review]
Hi Dzaru, there are several things that need to be fixed before this PR can be merged

1. The text color still doesn't match the one in the figma

2. **src/app/articles/hero-background.css**
`.bg-hero-image {
  height: auto;
  min-height: 100%; 
}`
The CSS is straightforward and serves its purpose. However, consider using Tailwind's utility classes for consistency across the project. Tailwind CSS, especially with JIT mode, offers fine-grained control and can significantly reduce the need for custom CSS, leading to a more maintainable codebase.

3. **src/app/articles/page.tsx**
```
`const scrollAnimation = () => {
  const targetPosition = 700;

  window.scrollTo({
    top: targetPosition,
    behavior: 'smooth'
  });
};`
```

The use of inline styles and direct manipulation of DOM elements (like window.scrollTo) is generally discouraged in favor of leveraging Next.js's routing mechanisms. Consider using the Link component from next/link for navigation, which supports smooth scrolling with the scroll prop.

**Review by dzarurizkyy — COMMENTED** [review]
Completed changing from using dom effect method to next link, converting previous native CSS styling method to using Tailwind CSS, and finally adjusting colors according in Figma.

**Review by candidatecollege — CHANGES_REQUESTED** [review]
The JavaScript function for smooth scrolling (e.g., `window.scrollTo`) is imperative and not aligned with React's declarative nature. A more React-friendly approach should be considered.

**Suggested Change**:
Utilize a combination of React `refs `and the `scrollIntoView ` method for a more integrated and declarative approach to handling smooth scrolling within React components.

**Example**:
```
import { useRef } from 'react';

const MyComponent = () => {
  const myRef = useRef(null);

  const scrollToRef = () => myRef.current?.scrollIntoView({ behavior: 'smooth' });

  return (
    <>
      <button onClick={scrollToRef}>Scroll Down</button>
      <div ref={myRef}>Scroll Target</div>
    </>
  );
};
```

**Comment by candidatecollege** [comment]
If there are any problems or difficulties related to this feedback, please contact me via personal chat.

**Review by candidatecollege — APPROVED** [review]
Good to go

**Pull request merged**
